from backend.prompts_local.en import *


# from langsmith import Client
# client = Client()
# fetch from langsmith
# ROUTER_SYSTEM_PROMPT = (
#     client.pull_prompt("url")
#     .messages[0]
#     .prompt.template
# )

"""Default prompts."""

ROUTER_SYSTEM_PROMPT = ROUTER_SYSTEM_PROMPT_STR

GENERATE_QUERIES_SYSTEM_PROMPT = GENERATE_QUERIES_SYSTEM_PROMPT_STR

MORE_INFO_SYSTEM_PROMPT = MORE_INFO_SYSTEM_PROMPT_STR

RESEARCH_PLAN_SYSTEM_PROMPT = RESEARCH_PLAN_SYSTEM_PROMPT_STR

GENERAL_SYSTEM_PROMPT = GENERAL_SYSTEM_PROMPT_STR

RESPONSE_SYSTEM_PROMPT = RESPONSE_SYSTEM_PROMPT_STR

GET_AND_UPDATE_PET_INFO_SYSTEM_PROMPT = GET_AND_UPDATE_PET_INFO_SYSTEM_PROMPT_STR
